package leet_code.Problem_879_Hard_Profitable_Schemes;

import java.util.*;

/**
 * Problem 879: Profitable Schemes
 * https://leetcode.com/problems/profitable-schemes/
 */
public class Solution {

    /**
     * Calculates the number of schemes with at most n members and at least
     * minProfit.
     * Strategy: 2D Dynamic Programming (Knapsack variant).
     * 
     * @param n         Maximum number of members.
     * @param minProfit Minimum profit required.
     * @param group     Members required for each crime.
     * @param profit    Profit generated by each crime.
     * @return Total schemes modulo 10^9 + 7.
     * 
     *         Tóm tắt chiến lược:
     *         1. Dùng mảng dp[i][j] lưu số cách sử dụng i thành viên để có ít nhất
     *         j lợi nhuận.
     *         2. Duyệt qua từng tội phạm. Với mỗi tội phạm, ta cập nhật lại bảng
     *         dp.
     *         Duyệt ngược từ n xuống group[k] để tránh dùng một tội phạm nhiều lần
     *         (giống bài toán cái túi 0/1).
     *         3. Lợi nhuận j + p được giới hạn tối đa ở minProfit vì ta chỉ cần
     *         biết nó
     *         đã đạt ngưỡng hay chưa.
     */
    public int profitableSchemes(int n, int minProfit, int[] group, int[] profit) {
        int MOD = 1_000_000_007;

        // dp[members_used][at_least_profit]
        int[][] dp = new int[n + 1][minProfit + 1];

        // Base case: 0 members, 0 profit = 1 scheme (doing nothing)
        dp[0][0] = 1;

        for (int k = 0; k < group.length; k++) {
            int g = group[k];
            int p = profit[k];

            // Iterate backwards to allow 0/1 knapsack updates
            for (int i = n; i >= g; i--) {
                for (int j = minProfit; j >= 0; j--) {
                    // Capping the profit at minProfit
                    int nextProfit = Math.min(minProfit, j + p);

                    dp[i][nextProfit] = (dp[i][nextProfit] + dp[i - g][j]) % MOD;
                }
            }
        }

        // Sum all schemes that use any number of members (0 to n)
        // and reach exactly minProfit.
        int totalSchemes = 0;
        for (int i = 0; i <= n; i++) {
            totalSchemes = (totalSchemes + dp[i][minProfit]) % MOD;
        }

        return totalSchemes;
    }

    public static void main(String[] args) {
        Solution sol = new Solution();

        int[] g1 = { 2, 2 };
        int[] p1 = { 2, 3 };
        System.out.println("Schemes: " + sol.profitableSchemes(5, 3, g1, p1)); // 2

        int[] g2 = { 2, 3, 5 };
        int[] p2 = { 6, 7, 8 };
        System.out.println("Schemes: " + sol.profitableSchemes(10, 5, g2, p2)); // 7
    }
}
