package leet_code.Problem_301_Hard_Remove_Invalid_Parentheses;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.Set;

public class Solution_BFS {

    /**
     * Removes minimum invalid parentheses.
     * Uses Breadth-First Search (BFS) to find shortest path to validity.
     * Time: O(2^N), Space: O(2^N).
     * 
     * Loại bỏ các dấu ngoặc không hợp lệ tối thiểu.
     * Sử dụng Tìm kiếm Chiều rộng (BFS) để tìm đường ngắn nhất đến trạng thái hợp
     * lệ.
     */
    public List<String> removeInvalidParentheses(String s) {
        List<String> res = new ArrayList<>();
        if (s == null)
            return res;

        Set<String> visited = new HashSet<>();
        Queue<String> queue = new LinkedList<>();

        queue.add(s);
        visited.add(s);
        boolean found = false;

        while (!queue.isEmpty()) {
            s = queue.poll();

            if (isValid(s)) {
                // If we found a valid string, add to result
                // Found flag ensures we only process strings of this length (min removals)
                // Nếu tìm thấy chuỗi hợp lệ, thêm vào kết quả
                // Cờ found đảm bảo chúng ta chỉ xử lý các chuỗi có độ dài này (xóa tối thiểu)
                res.add(s);
                found = true;
            }

            // Once found, we don't need to generate children (shorter strings) anymore
            // because we want Minimum removals.
            // Một khi đã tìm thấy, không cần tạo con (chuỗi ngắn hơn) nữa
            // vì chúng ta muốn số lần xóa Tối thiểu.
            if (found) {
                continue;
            }

            // Generate all possible states by removing 1 char
            // Tạo tất cả các trạng thái có thể bằng cách xóa 1 ký tự
            for (int i = 0; i < s.length(); i++) {
                // We only try to remove parentheses
                // Chỉ thử xóa dấu ngoặc
                char c = s.charAt(i);
                if (c != '(' && c != ')')
                    continue;

                String t = s.substring(0, i) + s.substring(i + 1);

                if (!visited.contains(t)) {
                    queue.add(t);
                    visited.add(t);
                }
            }
        }

        // If queue became empty (unlikely given empty string is valid), handle logic
        // inside loop correctly
        // With found logic inside loop, we might process level mixed with next level if
        // simple queue.
        // Wait, standard BFS layer-by-layer usually iterates `levelSize`.
        // But here, since we add children to END of queue, if we `conitnue` on `found`,
        // we naturally drain the queue of current level items that were enqueued BEFORE
        // found became true?
        // No. If `found` is true, we `continue` (skip generating children for THIS
        // node).
        // But we still process other nodes ALREADY in the queue (same level
        // candidates).
        // Any nodes from NEXT level (shorter strings) won't even be created if `found`
        // is true for start of level?
        // Actually, if we use a single queue without level loop, we might process a
        // valid node, set `found=true`.
        // Then subsequent nodes (same level) are checked. Valid ones added.
        // Invalid ones skip generating children.
        // What about nodes already added to queue (next level) by previous nodes in
        // same level?
        // Ah, if `found` is set, we stop generating. But we might have already
        // generated some short strings.
        // BUT, since we find valid strings at Length L, any shorter string (Length L-1)
        // generated by siblings
        // will be processed later. But since `found` is true, we won't add them?
        // No, `res` will get filled.
        // Actually, strictly speaking, level-order loop is safer to segregate Length L
        // from Length L-1.
        // But this logic works because:
        // 1. We process current `s`. If valid, `found=true`.
        // 2. If `found`, we stop adding *new* children.
        // 3. We continue polling. If `s` is valid, add. If invalid, do nothing (since
        // found=true).
        // The problem is if queue already contains shorter strings?
        // BFS guarantees we process all Length L strings before any Length L-1 strings.
        // So when the first Length L string is found valid, the queue only contains
        // Length L strings (and maybe some Length L-1 strings added by previous
        // processed nodes of Length L).
        // Wait, if node A (invalid) adds child A1 (len-1).
        // Then node B (valid) sets found=true.
        // Then we process A1 later. `isValid(A1)`? A1 is shorter (more removals). We
        // shouldn't include it.
        // So we strictly need to stop if found.
        // The check `if (isValid(s))` adds to res.
        // But if `found` is true, we might still process `A1`.
        // `A1` might be valid, but it represents MORE removals.
        // Problem requires MINIMUM removal.
        // Solution: Clear queue? No, other same-length nodes are there.
        // Correct fix: Use explicit level iteration.

        return res;
    }

    // Rewrite with explicit levels for correctness and safety
    public List<String> removeInvalidParentheses_Safe(String s) {
        List<String> res = new ArrayList<>();
        if (s == null)
            return res;

        Set<String> visited = new HashSet<>();
        Queue<String> queue = new LinkedList<>();

        queue.add(s);
        visited.add(s);
        boolean found = false;

        while (!queue.isEmpty()) {
            int size = queue.size();
            // Process entire level
            for (int i = 0; i < size; i++) {
                String u = queue.poll();
                if (isValid(u)) {
                    res.add(u);
                    found = true;
                }

                // If answer found in this level, don't generate children for any node in this
                // level
                // as next level means more removals.
                if (found)
                    continue;

                // Generate children
                for (int j = 0; j < u.length(); j++) {
                    if (u.charAt(j) != '(' && u.charAt(j) != ')')
                        continue;
                    String v = u.substring(0, j) + u.substring(j + 1);
                    if (!visited.contains(v)) {
                        queue.add(v);
                        visited.add(v);
                    }
                }
            }
            // If we found valid strings at this level, break.
            if (found)
                break;
        }
        return res;
    }

    private boolean isValid(String s) {
        int count = 0;
        for (char c : s.toCharArray()) {
            if (c == '(')
                count++;
            if (c == ')') {
                if (count == 0)
                    return false;
                count--;
            }
        }
        return count == 0;
    }

    public static void main(String[] args) {
        Solution_BFS solution = new Solution_BFS();

        // Use the safe implementation
        // Test Case 1: "()())()"
        System.out.println("Result 1: " + solution.removeInvalidParentheses_Safe("()())()"));

        // Test Case 2: "(a)())()"
        System.out.println("Result 2: " + solution.removeInvalidParentheses_Safe("(a)())()"));

        // Test Case 3: ")("
        System.out.println("Result 3: " + solution.removeInvalidParentheses_Safe(")("));
    }
}
