package leet_code.Problem_306_Medium_Additive_Number;

import java.math.BigInteger;

public class Solution_Iterative {

    /**
     * Checks if the string forms an additive sequence.
     * Uses Iterative generation of first two numbers.
     * Time: O(N^3), Space: O(N).
     * 
     * Kiểm tra xem chuỗi có tạo thành dãy cộng không.
     * Sử dụng sinh lặp hai số đầu tiên.
     */
    public boolean isAdditiveNumber(String num) {
        int n = num.length();
        // At least 3 numbers needed.
        if (n < 3)
            return false;

        // Loop for length of first number
        // Vòng lặp cho độ dài số đầu tiên
        // i is the END index (inclusive) of first number
        for (int i = 0; i < n / 2 + 1; i++) { // n1 length roughly max n/2

            // Loop for length of second number
            // j is the END index (inclusive) of second number
            // n/3*2 is roughly limit, but simpler to go up to n-1 with check
            // j starts from i+1
            for (int j = i + 1; j < n - 1; j++) {

                // Parse first two numbers
                String s1 = num.substring(0, i + 1);
                String s2 = num.substring(i + 1, j + 1);

                // Validate leading zeros
                if (s1.length() > 1 && s1.charAt(0) == '0')
                    break; // Invalid n1, break inner loop? Yes, longer won't help if starts with 0
                if (s2.length() > 1 && s2.charAt(0) == '0')
                    continue; // Invalid n2, continue to longer n2? No, if '0...' invalid, '0...x' also
                              // invalid. Break.
                // Wait, if s2 is "0", it's valid. If "05", invalid.
                // Break inner loop is correct for s1 leading zero.
                // For s2? If s2 starts with '0', only "0" is allowed. Any longer s2 starting
                // with '0' is invalid.
                // So if s2 is invalid leading zero, break inner loop.
                if (s2.length() > 1 && s2.charAt(0) == '0')
                    break;

                if (isValid(s1, s2, j + 1, num)) {
                    return true;
                }
            }
        }

        return false;
    }

    // Check if the rest of string matches sequence generated by n1, n2
    // Kiếm tra phần còn lại của chuỗi có khớp với dãy được tạo bởi n1, n2 không
    private boolean isValid(String s1, String s2, int startIndex, String num) {
        BigInteger n1 = new BigInteger(s1);
        BigInteger n2 = new BigInteger(s2);

        while (startIndex < num.length()) {
            BigInteger sum = n1.add(n2);
            String sumStr = sum.toString();

            if (!num.startsWith(sumStr, startIndex)) {
                return false;
            }

            startIndex += sumStr.length();
            n1 = n2;
            n2 = sum;
        }

        return true;
    }

    public static void main(String[] args) {
        Solution_Iterative solution = new Solution_Iterative();

        // Test Case 1: "112358" -> true
        System.out.println("Result 1: " + solution.isAdditiveNumber("112358"));

        // Test Case 2: "199100199" -> true
        System.out.println("Result 2: " + solution.isAdditiveNumber("199100199"));

        // Test Case 3: "1023" -> false (1, 0, 1 -> "1", "0", "1" -> "101" != "1023")
        System.out.println("Result 3: " + solution.isAdditiveNumber("1023"));
    }
}
